### ISSUE TITLE
[ERROR] if (!note.length) note = null;

### ISSUE THREAD

**Issue by GhostieSpook** [hanahaneull/Discord-Sp00kbot#1]
```
ghostiespook@Ghosties-MacBook-Pro Discord-Sp00kbot-master % node index.js
/Users/ghostiespook/Desktop/Discord-Sp00kbot-master/node_modules/discord.js/src/client/websocket/packets/handlers/Ready.js:41
        if (!note.length) note = null;
                  ^

TypeError: Cannot read property 'length' of null
    at ReadyHandler.handle (/Users/ghostiespook/Desktop/Discord-Sp00kbot-master/node_modules/discord.js/src/client/websocket/packets/handlers/Ready.js:41:19)
    at WebSocketPacketManager.handle (/Users/ghostiespook/Desktop/Discord-Sp00kbot-master/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:108:65)
    at WebSocketConnection.onPacket (/Users/ghostiespook/Desktop/Discord-Sp00kbot-master/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:336:35)
    at WebSocketConnection.onMessage (/Users/ghostiespook/Desktop/Discord-Sp00kbot-master/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:299:17)
    at WebSocket.onMessage (/Users/ghostiespook/Desktop/Discord-Sp00kbot-master/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:314:20)
    at Receiver.receiverOnMessage (/Users/ghostiespook/Desktop/Discord-Sp00kbot-master/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (events.js:314:20)
    at Receiver.dataMessage (/Users/ghostiespook/Desktop/Discord-Sp00kbot-master/node_modules/ws/lib/receiver.js:413:14)
    at Receiver.getData (/Users/ghostiespook/Desktop/Discord-Sp00kbot-master/node_modules/ws/lib/receiver.js:352:17)
ghostiespook@Ghosties-MacBook-Pro Discord-Sp00kbot-master %
```

**Comment by hanahaneull** [comment]
This is discord.js problem when you tried to login with user token.

# FIX
1. open ``node_modules`` folder
2. open ``discord.js`` folder
3. open ``src`` folder
4. open ``client`` folder
5. open ``websocket`` folder
6. open ``packets`` folder
7. open ``handler`` folder
8. open ``Ready.js`` file with notepad or your favorite text editor (Right click and open with...)
9. Goto line 41 or CTRL + F ``if (!note.length) note = null;``
10. change to ``//if (!note.length) note = null;``
11. And save (CTRL + S)

**Comment by GhostieSpook** [comment]
Sweet. Works now. Also, one question Is multi-server support a thing. if no that's fine. Just wondering.

**Comment by hanahaneull** [comment]
Yeah, I can work on that. For now just run multiple client to have multi-server support.

**Comment by hanahaneull** [comment]
@GhostieSpook just pushed new update for multi-server support ^^

**Comment by GhostieSpook** [comment]
Damn you're fast keep up the amazing work <3
